version: '3.8'

services:
  pgsql:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: luxt_project_db
      POSTGRES_USER: sail
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
